language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer self-update
  - composer install
after_script:
  - vendor/bin/test-reporter
script:
  - ./phpunit.sh
notfications:
  email:
    recipients:
      - matthew@matthewsetter.com
    on_success: always
    on_failure: always
  irc: 
    channels:
      - "irc.freenode.net#conetix-blog"
    use_notice: true
    on_success: always
    on_failure: always
    skip_join: true
  hipchat: 
    rooms:
      - NRCYMdcSV1Z2jMFqhtGnFrasIOrKet9XYhPMJNZA@Matthewsetter
    format: html
    notify: true
    on_success: always
    on_failure: always
addons:
  code_climate:
    repo_token: 6fecc63f321bc0db45f9bac1194f4deeebe8b1a32dedc722e83ae23a9730f268
