language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - phpenv config-add phpconfig.ini
  - composer self-update
  - composer install
after_script:
  - CODECLIMATE_REPO_TOKEN="6fecc63f321bc0db45f9bac1194f4deeebe8b1a32dedc722e83ae23a9730f268" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
script:
  - ./phpunit.sh
notfications:
  email:
    recipients:
      - matthew@matthewsetter.com
    on_success: always
    on_failure: always
  irc: 
    channels:
      - "irc.freenode.net#conetix-blog"
    use_notice: true
    on_success: always
    on_failure: always
    skip_join: true
  hipchat: 
    rooms:
      - NRCYMdcSV1Z2jMFqhtGnFrasIOrKet9XYhPMJNZA@Matthewsetter
    format: html
    notify: true
    on_success: always
    on_failure: always
addons:
  code_climate:
    repo_token: 6fecc63f321bc0db45f9bac1194f4deeebe8b1a32dedc722e83ae23a9730f268
