language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer self-update
  - composer install
script:
  - ./phpunit.sh
notfications:
  email:
    recipients:
      - matthew@matthewsetter.com
  irc: "irc.freenode.net#conetix-blog"
  hipchat: 
    rooms:
      - NRCYMdcSV1Z2jMFqhtGnFrasIOrKet9XYhPMJNZA@Matthewsetter
    format: html
  on_success: always
  on_failure: always
