language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
before_script:
  - composer self-update
  - composer install
script:
  - ./phpunit.sh
notfications:
  email:
    - matthew@matthewsetter.com
  on_success: always
  on_failure: always
